server:
  port: 9090                # Устанавливаем порт, на котором будет работать api-gateway

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true         # Включаем автоматическое создание маршрутов на основе Eureka
          lower-case-service-id: true   # Названия сервисов будут в нижнем регистре (удобнее для URL)

management:
  endpoints:
    web:
      exposure:
        include: "*" # или: "health,info,env" если хочешь выборочно 
  endpoint:
    gateway:
      enabled: true  # 👈 важно: включает /actuator/gateway/*
