# ================================
# Настройки API Gateway
# ================================
server:
  port: 9090  # Порт, на котором запускается gateway (http://localhost:9090)

spring:
  cloud:
    gateway:
      routes:
        # ЯВНО задаём маршрут в user-service через localhost:8081
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**  # всё, что начинается с /api/users будет проксироваться
            
      # ================================
      # Отключаем DiscoveryLocator (он сейчас не работает)
      # ================================
      discovery:
        locator:
          enabled: false  # ❌ Отключаем автоматическую маршрутизацию на основе Eureka
          #lower-case-service-id: true

# ================================
# Настройки Spring Boot Actuator
# ================================
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Включаем все actuator endpoints: /actuator/health, /actuator/gateway/routes и т.д.

  endpoint:
    gateway:
      enabled: true  # Включаем специальные маршруты gateway, например /actuator/gateway/routes
  # ⬇⬇⬇ ВАЖНО: этот блок необходим для Spring Boot 3.1+
  web:
    exposure:
      include: "*"
