# ================================
# Настройки API Gateway
# ================================
server:
  port: 9090  # Порт, на котором запускается gateway (http://localhost:9090)

spring:
  cloud:
    gateway:
      routes:
        # ================================
        # 🎯 1. Классический маршрут: /user-service/**
        # Проксирует запросы в user-service напрямую
        # Например: /user-service/api/users → http://localhost:8081/api/users
        # ================================
        - id: user-service
          uri: http://localhost:8081  # Адрес, на который проксируем
          predicates:
            - Path=/user-service/**  # Какие пути обрабатываем

        # ================================
        # 🎯 2. Красивый маршрут: /api/users/**
        # Без лишнего префикса, напрямую
        # Например: /api/users → http://localhost:8081/api/users
        # ================================
        - id: user-service-clean
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

      # ================================
      # Отключаем DiscoveryLocator (он сейчас не работает)
      # ================================
      discovery:
        locator:
          enabled: false  # ❌ Отключаем автоматическую маршрутизацию на основе Eureka
          lower-case-service-id: true

# ================================
# Настройки Spring Boot Actuator
# ================================
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Включаем все actuator endpoints: /actuator/health, /actuator/gateway/routes и т.д.

  endpoint:
    gateway:
      enabled: true  # Включаем специальные маршруты gateway, например /actuator/gateway/routes
