server:
  port: 9091

spring:
  application:
    name: auth-service

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - env

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
