server:
  port: 9091

spring:
  application:
    name: auth-service

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - env
