# ? ????????? ??????????? HTTP-??????? (Tomcat ?? ?????????)
server:
  port: 8081  # user-service ????? ???????? ?? ?????? http://localhost:8081

# ? ???????? ????????? Spring Boot ??????????
spring:
  application:
    name: user-service  # ??? ???????, ??????? ????? ????? ? Eureka, ?????, Zipkin, Spring Cloud Config ? ?.?.

  # ?? ???????????? ??????????? ? PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/interviewproject_user_service  # ?????? ??????????? ? ??
    username: postgres         # ??? ???????????? ??
    password: postgres         # ?????? ????????????

  # ? ???????????? JPA (Hibernate ? ?????????? JPA)
  jpa:
    hibernate:
      ddl-auto: update         # ????? ?????? ? ??: update = ????????? ????? ??? ??????? (??? dev); ? ????? ????? validate ??? none
    show-sql: true             # ?????????? SQL-??????? ? ??????? (?????? ??? ???????)
    properties:
      hibernate:
        format_sql: true       # ??????? ??????????? SQL ? ???????
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # ??????? SQL, ??????????????? PostgreSQL

  # ? ????????? Apache Kafka (????? ??? ????????????? ? Cloud Stream, ?? ????? ???????? ??? ???, ???? ??????????? ?????? stream)
  kafka:
    bootstrap-servers: localhost:9092  # ????? ??????? Kafka (?????? ??? ??????????)
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # ???????????? ?????? ????????? (?????? ??????)
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # ???????????? ???????? ?????????
    consumer:
      group-id: user-group  # ID ?????? Kafka-?????????? (???? ?????? ??????? ???????)
      auto-offset-reset: earliest  # ???? ??? offset ? ???????? ? ?????? ??????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # ?? ????????? Spring Cloud Stream (?????????? ??? Kafka/RabbitMQ)
  cloud:
    config:
      discovery:
        enabled: false
    stream:
      binders:  # ?????????? binder'?? (? ????? ?????? ? Kafka)
        kafka:  # ??? binder'?, ?? ????? ?? ???? ????????? ? binding'??
          type: kafka  # ??? binder'? (Kafka, Rabbit ? ??.)
          environment:  # ????? ?????????????? ???????? ????? ?????? ??? ????? binder'?
            spring:
              kafka:
                bootstrap-servers: localhost:9092  # ????? Kafka ???????
      bindings:
        userCreated-out-0:  # ?????????? output-????? (??? ???????? ????)
          destination: user-created-topic  # ??? Kafka ??????, ? ??????? ????? ???? ??????????
          content-type: application/json   # ???????????? ????????? ? JSON
          binder: kafka                    # ????? binder ???????????? (?? ????? ?? ?????? ????)

        userCreated-in-0: # ? Consumer (????? ?? Kafka)
          destination: user-created-topic
          group: user-group
          content-type: application/json
          binder: kafka


# ? ????????? Spring Boot Actuator ? ??? ???????, ????? ??????????? ? ???????? ??????????
management:
  endpoints:
    web:
      exposure:
        include: "*"  # ???????? ??? endpoints (????????: /actuator/health, /actuator/metrics)
  endpoint:
    health:
      show-details: always  # ?????????? ??????????? ? /actuator/health (????????, ????????? ??, Kafka ? ?.?.)
